### ISSUE TITLE
Origin of MP00301_KL10PV_Jun80.pdf

### ISSUE THREAD

**Issue by pmcjones** [alanmimms/kl10#2]
This looks like a very interesting project. One suggestion: in README.md, change:

	https://archive.org/details/bitsavers_decpdp10KL0_67493660

to:

	http://bitsavers.org/pdf/dec/pdp10/KL10/MP00301_KL10PV_Jun80.pdf

This will acknowledge Al Kossow’s work in tracking down and scanning this document, and will help others understand the origin of the document and perhaps to find related documents of interest.

**Comment by alanmimms** [comment]
I changed the README to show Al's considerable contribution that has enabled me to do this.
